version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: symfony-app
    volumes:
      - ./symfony_app:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db_dev
      - db_test

  db_dev:
    image: mariadb:latest
    container_name: symfony-db-dev
    environment:
      MYSQL_ROOT_PASSWORD: dev_root_password
      MYSQL_DATABASE: symfony_dev_db
      MYSQL_USER: symfony_user
      MYSQL_PASSWORD: symfony_password
    ports:
      - "3307:3306"
    volumes:
      - db_dev_data:/var/lib/mysql

  db_test:
    image: mariadb:latest
    container_name: symfony-db-test
    environment:
      MYSQL_ROOT_PASSWORD: test_root_password
      MYSQL_DATABASE: symfony_test_db
      MYSQL_USER: symfony_test_user
      MYSQL_PASSWORD: symfony_test_password
    ports:
      - "3308:3306"
    volumes:
      - db_test_data:/var/lib/mysql

volumes:
  db_dev_data:
  db_test_data:
